const colombia= [];
colombia.push({
    name:"juanita",
    salary:1000});
colombia.push({
    name:"sara",
    salary:1400});
colombia.push({
    name:"alberto",
    salary:1500});
colombia.push({
    name:"esteban",
    salary:3500});    
// console.log(colombia);
colombia.push({
    name:"juanita",
    salary:1000});
colombia.push({
    name:"sara",
    salary:1400});
colombia.push({
    name:"alberto",
    salary:1500});
colombia.push({
    name:"esteban",
    salary:3500});    
// console.log(colombia);
colombia.push({
    name:"juanita",
    salary:1000});
colombia.push({
    name:"sara",
    salary:1400});
colombia.push({
    name:"alberto",
    salary:1500});
colombia.push({
    name:"esteban",
    salary:3500});    
console.log(colombia);
colombia.push({
    name:"juanita",
    salary:1000});
colombia.push({
    name:"sara",
    salary:1300});
colombia.push({
    name:"alberto",
    salary:1500});
colombia.push({
    name:"esteban",
    salary:2500});    
// console.log(colombia);
colombia.push({
    name:"juanita",
    salary:1400});
colombia.push({
    name:"sara",
    salary:1450});
colombia.push({
    name:"alberto",
    salary:1570});
colombia.push({
    name:"esteban",
    salary:3200});    
// console.log(colombia);